---
title: "North Atlantic Albacore MSE"
format:
  html:
    toc: true
    mainfont: Helvetica
    toc-location: left
    page-layout: full
number-sections: true
number-depth: 4
title-block-banner: "#000000"
title-block-banner-color: "#FFFFFF"
css: azti.css
embed-resources: true
html-table-processing: none
theme:
  - azti.scss
---

## Introduction

Welcome to the North Atlantic Albacore (N-ALB, *Thunnus alalunga*) MSE homepage.

This site contains links to documents, reports, and presentations related to the management strategy evaluation (MSE) process for N-ALB.

The MSE is being conducted with the open-source [FLBEIA](https://github.com/flr/FLBEIA) framework. The code for the NALB MSE is available in the [MSE GitHub repository](https://github.com/ICCAT/nalb-mse-2).

## MSE Trial Specification Document

This document describes the specifications for the operating models (OMs), candidate management procedures (CMPs), and performance indicators (PIs) that have been proposed and developed for the NALB fishery. It is a living document and will be continued to be updated so that it reflects the current state of the N-ALB MSE process.

The document can be found [here](https://iccat.github.io/nalb-mse-2/TechSpec/Trial_Specs.html).

## MSE Shiny App with Results

This application presents the main MSE results by using the FLBEIA Shiny App.

The application can be found [here](https://aztigps.shinyapps.io/shiny-flbeia/?dataset=ALB).

